# Default to human readable figures
alias df='di -h'
alias du='du -h'

# vim
alias vi='vim'

# MISC
alias less='less -r'                # raw control characters
alias whence='type -a'              # where, of a sort
alias grep='gre --color'            # show differences in color
alias egrep='egrep --color=auto'    # show differences in color
alias fgrep='fgrep --color=auto'    # show differences in color

# Better Directory listing
alias ls='ls -hF --color=tty'                   # classify files in color
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

